[package]
name = "map-reduce"
version = "0.1.0"
authors = ["Ertugrul Karademir <ekarademir@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"
futures = "0.3.5"
hyper = "0.13.7"
log = { version = "0.4.11", features = ["release_max_level_info"] }
tokio = { version = "0.2.22", features = ["full"] }
