version: "3.8"
services:
    master:
        build:
            context: .
            target: serve
        environment:
            - RUST_LOG=debug
            - MAPREDUCE__KIND=master
            - MAPREDUCE__HOST=http://master:3000
        ports:
            - 9001:3000
        volumes:
            - ./data:/root/data
    worker1:
        build:
            context: .
            target: serve
        environment:
            - RUST_LOG=debug
            - MAPREDUCE__KIND=worker
            - MAPREDUCE__MASTER=http://master:3000
            - MAPREDUCE__HOST=http://worker1:3000
        ports:
            - 9002:3000
        volumes:
            - ./data:/root/data
    worker2:
        build:
            context: .
            target: serve
        environment:
            - RUST_LOG=debug
            - MAPREDUCE__KIND=worker
            - MAPREDUCE__MASTER=http://master:3000
            - MAPREDUCE__HOST=http://worker2:3000
        ports:
            - 9003:3000
        volumes:
            - ./data:/root/data
